module.exports = {
	name: 'name must be longer than 2 symbols',
	email: 'not valid email',
	phone: 'not valid phone number',
	extend: 'extend field error',
	id: 'id must be longer than 19 characters',
	address: 'address must be longer than 7 characters',
	password: 'password must be longer than 7 characters',
	tosAgreement: 'you shoud accept our Terms of Service',
	parseError: 'json body parse error',
	userCreate: 'user create error',
	userRead: 'user read error',
	userUpdate: 'user update error',
	userDelete: 'user delete error',
	tokenCreate: 'token create error',
	tokenRead: 'token read error',
	tokenDelete: 'token delete error',
	noDataForUpdating: 'doesn\'t have data for updating',
	auth: 'autorization error',
	EEXIST: 'can\'t create, file exists',
	WRONG_PSWD: 'wrong password',
	TOKEN_EXPIRED: 'token is expired',
	TOKEN_NOT_EXIST: 'token not exist',
	ENOENT: 'can\'t read, file not exist'
};
